# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
