# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_myuser_sex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
