# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_drug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
        migrations.AddField(
            model_name='drug',
            name='caution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='effect',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='eng_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='kor_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='imprinted_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='ref_img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='shape',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='way_to_store',
            field=models.TextField(null=True),
        ),
    ]
