# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20170818_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='info',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='ref_img',
        ),
    ]
