# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_auto_20170821_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='eng_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='kor_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
