# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_auto_20170821_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='ref_img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
