# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 07:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_drug_ref_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='imprinted_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
