# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 07:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_auto_20170828_1625'),
    ]

    operations = [
		HStoreExtension(),
    ]
