# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_hstore_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='imprinted_text',
        ),
        migrations.AddField(
            model_name='drug',
            name='imprint',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
