# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugs', '0014_auto_20170904_1212'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='kor_name',
            new_name='drug',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='email',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together=set([('user', 'drug')]),
        ),
    ]
