# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='icon',
            field=models.IntegerField(default=0),
        ),
    ]
