# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='email address'),
        ),
    ]
